services:
  - type: web
    name: nextjs-static
    runtime: static
    buildCommand: yarn; yarn build
    staticPublishPath: out
    pullRequestPreviewsEnabled: true # optional
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.11.0
